### ISSUE TITLE
I'm having trouble building with grunt

### ISSUE THREAD

**Issue by gavinengel** [rummelj/bindingjs#44]
I've getting many errors when I run grunt.  I am also missing the build/stagex files.

Here is what I see: https://gist.github.com/gavinengel/6699bcdf749eff4fb79e

**Comment by rummelj** [comment]
Hi Gavin,

Thanks for letting me know. I will look into this later tonight.

Best
Johannes

**Comment by rummelj** [comment]
Hi Gavin,

Unfortunately I can not reproduce the problem since I can build without errors. Could you please provide more information about your environment and/or any modifications you made? Those errors also look weird - it could be a problem with EcmaScript 6 in combination with your JSHint version (just a rough guess). Did you try `grunt --force`? Did you run `npm install`? Did you try a fresh checkout?

Best
Johannes

**Comment by gavinengel** [comment]
Ah, grunt --force got things working.  Thanks!

https://gist.github.com/gavinengel/86a38217436d13745566
